Added the models and routes(Sage Myers)
IanFlower/Mashed-Potato-Backend pull request #4
Opened 2024-10-14 19:15 UTC by sageMyers

2024-10-14 22:42 UTC, IanBirdcatcher requested changes
What are these tests in __tests__ and tests.yml in the workflows folder?
Why do we have tutorial code? tutorial.controller.js?
Why is the tutorial-backend.service in here? 

That's just what I immediately see but there appear to be some incorrect files in here.

2024-10-21 14:46 UTC, Loganmurrie approved these changes

2024-10-21 14:46 UTC, Loganmurrie approved these changes

2024-10-21 14:47 UTC, Loganmurrie approved these changes

2024-10-21 14:47 UTC, Loganmurrie approved these changes

2024-10-21 14:47 UTC, Loganmurrie approved these changes

2024-10-21 14:48 UTC, Loganmurrie approved these changes

2024-10-21 14:48 UTC, Loganmurrie approved these changes

2024-10-21 14:48 UTC, Loganmurrie approved these changes

2024-10-21 14:49 UTC, Loganmurrie approved these changes

2024-10-21 14:52 UTC, IanBirdcatcher approved these changes

2024-10-21 14:52 UTC, merged